######################################################################
# Automatically generated by qmake (3.0) Fri Feb 20 17:24:14 2015
######################################################################

TEMPLATE = app
TARGET = projet
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += Image.h Window.h
SOURCES += Image.cpp main.cpp Window.cpp
