######################################################################
# Automatically generated by qmake (3.0) Thu Feb 26 12:39:45 2015
######################################################################

TEMPLATE = app
TARGET = projet_BDM
INCLUDEPATH += . lib
QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets printsupport

# Input
HEADERS += Image.h Window.h lib/qcustomplot.h
SOURCES += Image.cpp main.cpp Window.cpp lib/qcustomplot.cpp
